add chksums + makenek fixes

diff --git a/3rd_party/cvode/install b/3rd_party/cvode/install
--- a/3rd_party/cvode/install
+++ b/3rd_party/cvode/install
@@ -2,6 +2,7 @@
 set -e
 
 VER=2.7.0
+CHKSUM=3559c375ce9f875542e4a39978908f91792e6d57
 
 if [ "$1" == "clean" ]; then
   rm -rf sundials lib include 2>/dev/null 
@@ -18,6 +19,11 @@ fi
 
 rm -rf sundials 2>/dev/null
 mkdir sundials
+if ! echo "$CHKSUM  sundials-$VER.tar.gz" | shasum -a 1 -c - 2>/dev/null ; then
+  echo 'Invalid checksum!'
+  rm -rf sundials-$VER.tar.gz 
+  exit 1
+fi
 tar -zxvf sundials-$VER.tar.gz -C ./sundials --strip-components=1
 cd sundials
 mkdir -p build
diff --git a/3rd_party/gslib/install b/3rd_party/gslib/install
--- a/3rd_party/gslib/install
+++ b/3rd_party/gslib/install
@@ -2,6 +2,7 @@
 set -e
 
 VER=1.0.3
+CHKSUM=79dd31cae5653f2e9470845ff1096fb82df79ba3
 
 if [ "$1" == "clean" ]; then
   rm -rf gslib lib include 2>/dev/null 
@@ -18,6 +19,11 @@ fi
 
 rm -rf gslib 2>/dev/null
 mkdir gslib 
+if ! echo "$CHKSUM  v$VER.tar.gz" | shasum -a 1 -c - 2>/dev/null ; then
+  echo 'Invalid checksum!'
+  rm -rf v$VER.tar.gz
+  exit 1
+fi
 tar -zxvf v$VER.tar.gz -C ./gslib --strip-components=1
 cd gslib
 set -x
diff --git a/3rd_party/hypre/install b/3rd_party/hypre/install
--- a/3rd_party/hypre/install
+++ b/3rd_party/hypre/install
@@ -2,6 +2,7 @@
 set -e
 
 VER=2.15.1
+CHKSUM=655cbb848f5805512bf24b8ca5d7e923a70151fa
 
 if [ "$1" == "clean" ]; then
   rm -rf hypre lib include 2>/dev/null
@@ -17,6 +18,11 @@ fi
 
 rm -rf hypre 2>/dev/null
 mkdir hypre
+if ! echo "$CHKSUM  v$VER.tar.gz" | shasum -a 1 -c - 2>/dev/null ; then
+  echo 'Invalid checksum!'
+  rm -rf v$VER.tar.gz
+  exit 1
+fi
 tar -zxvf v$VER.tar.gz -C ./hypre --strip-components=1
 cd hypre
 mkdir -p build
diff --git a/3rd_party/parMETIS/install b/3rd_party/parMETIS/install
--- a/3rd_party/parMETIS/install
+++ b/3rd_party/parMETIS/install
@@ -2,6 +2,7 @@
 set -e
 
 VER=4.0.3
+CHKSUM=e0df69b037dd43569d4e40076401498ee5aba264
 
 if [ "$1" == "clean" ]; then
   rm -rf parMETIS bin lib include 2>/dev/null 
@@ -15,7 +16,12 @@ fi
 wget --no-check-certificate -O v$VER.tar.gz http://glaros.dtc.umn.edu/gkhome/fetch/sw/parmetis/parmetis-$VER.tar.gz
 
 rm -rf parMETIS 2>/dev/null
-mkdir parMETIS 
+mkdir parMETIS
+if ! echo "$CHKSUM  v$VER.tar.gz" | shasum -a 1 -c - 2>/dev/null ; then
+  echo 'Invalid checksum!'
+  rm -rf v$VER.tar.gz
+  exit 1
+fi 
 tar -zxvf v$VER.tar.gz -C ./parMETIS --strip-components=1
 cd parMETIS
 
