Import latest updates (#609)
* Fix #474
* Add cgns2nek
* Add blasLapack as 3rd party
* Add nekconfig

diff --git a/3rd_party/cvode/install b/3rd_party/cvode/install
--- a/3rd_party/cvode/install
+++ b/3rd_party/cvode/install
@@ -2,6 +2,7 @@
 set -e
 
 VER=2.7.0
+CHKSUM=3559c375ce9f875542e4a39978908f91792e6d57
 
 if [ "$1" == "clean" ]; then
   rm -rf sundials lib include 2>/dev/null 
@@ -12,13 +13,19 @@ if [ -f ./lib/libsundials_fcvode.a ]; then
   exit 0
 fi
 
-if [ ! -f sundials-$VER.tar.gz ]; then
-  wget --no-check-certificate -O sundials-$VER.tar.gz https://computation.llnl.gov/projects/sundials/download/sundials-$VER.tar.gz
+if [ ! -f v$VER.tar.gz ]; then
+  wget --no-check-certificate -O v$VER.tar.gz https://computation.llnl.gov/projects/sundials/download/sundials-$VER.tar.gz
+  SUM=`openssl dgst -sha1 v$VER.tar.gz | sed 's/^.* //'`
+  if [ $SUM != $CHKSUM ] ; then
+    echo 'Invalid checksum!'
+    rm -rf v$VER.tar.gz
+    exit 1
+  fi
 fi
 
 rm -rf sundials 2>/dev/null
 mkdir sundials
-tar -zxvf sundials-$VER.tar.gz -C ./sundials --strip-components=1
+tar -zxvf v$VER.tar.gz -C ./sundials --strip-components=1
 cd sundials
 mkdir -p build
 cd build
diff --git a/3rd_party/gslib/install b/3rd_party/gslib/install
--- a/3rd_party/gslib/install
+++ b/3rd_party/gslib/install
@@ -1,7 +1,8 @@
 #!/bin/bash
 set -e
 
-VER=1.0.3
+VER=1.0.4
+CHKSUM=422cdd18e70a92ca6a08cca57b9fbb92a3c6e789
 
 if [ "$1" == "clean" ]; then
   rm -rf gslib lib include 2>/dev/null 
@@ -14,6 +15,12 @@ fi
 
 if [ ! -f v$VER.tar.gz ]; then
   wget --no-check-certificate -O v$VER.tar.gz http://github.com/gslib/gslib/archive/v$VER.tar.gz
+  SUM=`openssl dgst -sha1 v$VER.tar.gz | sed 's/^.* //'`
+  if [ $SUM != $CHKSUM ] ; then
+    echo 'Invalid checksum!'
+    rm -rf v$VER.tar.gz
+    exit 1
+  fi
 fi
 
 rm -rf gslib 2>/dev/null
diff --git a/3rd_party/hypre/install b/3rd_party/hypre/install
--- a/3rd_party/hypre/install
+++ b/3rd_party/hypre/install
@@ -2,6 +2,7 @@
 set -e
 
 VER=2.15.1
+CHKSUM=655cbb848f5805512bf24b8ca5d7e923a70151fa
 
 if [ "$1" == "clean" ]; then
   rm -rf hypre lib include 2>/dev/null
@@ -11,12 +12,20 @@ fi
 if [ -f ./lib/libHYPRE.a ]; then
   exit 0
 fi
+
 if [ ! -f v$VER.tar.gz ]; then
   wget --no-check-certificate -O v$VER.tar.gz https://github.com/LLNL/hypre/archive/v$VER.tar.gz 
+  SUM=`openssl dgst -sha1 v$VER.tar.gz | sed 's/^.* //'`
+  if [ $SUM != $CHKSUM ] ; then
+    echo 'Invalid checksum!'
+    rm -rf v$VER.tar.gz
+    exit 1
+  fi
 fi
 
 rm -rf hypre 2>/dev/null
 mkdir hypre
+
 tar -zxvf v$VER.tar.gz -C ./hypre --strip-components=1
 cd hypre
 mkdir -p build
