added some checks in maketools
git-svn-id: https://svn.mcs.anl.gov/repos/nek5/trunk/tools@200 24248562-e74d-0410-ab4b-d4d80c744c73

diff --git a/tools/maketools b/tools/maketools
--- a/tools/maketools
+++ b/tools/maketools
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # install path
-bin_nek_tools="$HOME/bin"
+bin_nek_tools="$HOME/bins"
 
 # compilers
 CC=pgcc
@@ -34,6 +34,22 @@ F77=pgf77
 
 ##################################
 
+which `echo $F77 | awk '{print $1}'` 1>/dev/null
+if [ $? -ne 0 ]; then
+  echo "FATAL ERROR: Cannot find $F77!"
+  exit 1
+fi
+
+which `echo $CC | awk '{print $1}'` 1>/dev/null
+if [ $? -ne 0 ]; then
+  echo "FATAL ERROR: Cannot find $CC!"
+  exit 1
+fi
+
+if [ ! -d $bin_nek_tools  ]; then
+  echo "FATAL ERROR: install path $bin_nek_tools does not exist!"
+  exit 1
+fi
 
 
 case $F77 in
